config/routes.rb
Rails.application.routes.draw do
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'sessions/new'
  resources 'users'
  
  namespace :admin do
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :masters, :apps, :articles, :campsites, :gears
  end
  
  resources :reviews, :campsites, :articles, :gears
  
  
  root 'pages#index'
  get 'pages/help'
  
  get  'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites',to: 'favorites#destroy'

  get 'comments/index'
  get 'comments/new' 
  post '/comments', to: "comments#create"
  delete '/comments', to: "comments#destroy"
end

app/models/app.rb
class App < ApplicationRecord
  has_many :masters
  has_many :articles
  has_many :gears
  has_many :campsites
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :master_id, presence: true
  validates :content, presence: true
  validates :image, presence: true
  default_scope -> { order(created_at: :desc) }
  
  mount_uploader :image, ImageUploader
  
  belongs_to :master
  has_many :reviews
end

app/models/campsite.rb
class Campsite < ApplicationRecord
  belongs_to :master
  has_many :reviews
  
  
  validates :master_id, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/gear.rb
class Gear < ApplicationRecord
  validates :master_id, presence: true
  
  belongs_to :master
  has_many :reviews
end

app/models/master.rb
class Master < ApplicationRecord
  validates :name,presence: true, length:{maximum:15}
  validates :login_id,presence: true, length:{maximum:15}
  validates :admin,presence: true
  
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]/
  validates :email,presence: true, format:{with:VALID_EMAIL_REGEX}
  
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])[a-z\d]{8,32}+\z/
  validates :password, presence: true, format:{with:VALID_PASSWORD_REGEX}
  
  has_secure_password
  
  has_many :users
  has_many :articles
  has_many :gears
  has_many :campsites
end

app/models/review.rb
class Review < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true
  default_scope -> { order(created_at: :desc) }
  
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  has_many :comments, dependent: :destroy
  has_many :comment_users, through: :comments, source: 'user'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,presence: true, length:{maximum:15}
  
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]/
  validates :email,presence: true, format:{with:VALID_EMAIL_REGEX}
  
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])[a-z\d]{8,32}+\z/
  validates :password, presence: true, format:{with:VALID_PASSWORD_REGEX}
  
  has_secure_password
  
  has_many :reviews, dependent: :destroy
  has_many :favorites
  has_many :favorite_reviews, through: :favorites, source: 'review'
  has_many :comments
  has_many :comments_reviews, through: :comments, source: 'review'
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :login_check
  def index
    @articles = Article.all
  end
  
  def show
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = admin_master.articles.new(article_params)
    if @article.save
      redirect_to ("/admin/articles"), success: '投稿に成功しました'
    else
      flash.now[:denger] = '投稿に失敗しました'
      render :new
    end
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find_by(id: params[:id])
    if @article.update(article_params)
      redirect_to ("/admin/articles"), success: '編集しました'
    else
      flash.now[:denger] = '編集に失敗しました'
      render :edit
    end
  end
  
    
  private
  def article_params
    params.require(:article).permit(:image, :title, :content).merge(master_id: admin_master.id)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  def index
    @gears = Gear.all
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/campsites_helper.rb
module CampsitesHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def create
    master = Master.find_by(email: params[:session][:email])
    if master && master.authenticate(params[:session][:password])
      log_in master
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end
  
  
  private
  def master_params
    params.require(:masters).permit(:login_id, :eamil, :password, :password_confirmation)
  end
  def log_in(master)
    session[:masters] = master.id
  end

  def log_out(master)
    session.delete(:masters)
    @current_master = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/articles/edit.html.erb
<body>
    <h1>管理画面</h1>
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <h1><%= link_to "Article", admin_articles_path %></h1>
        <h1><%= link_to "Gaers", admin_gears_path %></h1>
        <h1><%= link_to "Campsites", admin_campsites_path %></h1>
        <h1><%= link_to "Users", users_path %></h1>
      </ul>
    </div>
    <div class="table-responsive">
      <table class="table table-striped">
        <div class="article-new-wrapper">
          <div class="container">
            <div class="row">
              <div class="col-md-6 col-md-offset-3">
                <h1 class="text-center">ARTICLE 編集ページ</h1>
                <%= form_for @article,:url => {:action => :update} do |f| %>
                  <div class="form-group">
                    <%= f.label :image %>
                    <%= f.file_field :image %>
                  </div>
                  <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_area :title, class: 'form-control' %>
                  </div>
                  <div class="form-group">
                    <%= f.label :content %>
                    <%= f.text_area :content, class: 'form-control' %>
                  </div>
                  <%= f.submit '更新', class: 'btn btn-black btn-block' %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </table>
    </div>
</body>

app/views/admin/articles/index.html.erb
 <body>
    <h1>管理画面</h1>
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <h1><%= link_to "Article", admin_articles_path %></h1>
        <h1><%= link_to "Gaers", admin_gears_path %></h1>
        <h1><%= link_to "Campsites", admin_campsites_path %></h1>
        <h1><%= link_to "Users", users_path %></h1>
      </ul>
    </div>
    <div class="table-responsive">
      <table class="table table-striped">
      　<div class="review-index-wrapper">
          <div class="container">
            <div class="col-md-6 col-md-offset-3">
              <%= link_to 'New Article', new_admin_article_path, class: 'btn btn-primary' %>
            </div>
            <% @articles.each do |article| %>
              <div class="row">
                <div class="col-md-6 col-md-offset-3">
                  <div class="review-index-single">
                    <h2 class="review-author">
                      <%= article.title %>
                    </h2>
                    <%= image_tag article.image.url %>
                    <p class="article-text">
                      <%= article.content %>
                    </p>
                    <p><%= article.master.name %></p>
                    <%= link_to '編集', edit_admin_article_path(article), class: 'btn btn-primary' %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
    　</table>
    </div>
</body>

app/views/admin/articles/new.html.erb
<body>
    <h1>管理画面</h1>
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <h1><%= link_to "Article", admin_articles_path %></h1>
        <h1><%= link_to "Gaers", admin_gears_path %></h1>
        <h1><%= link_to "Campsites", admin_campsites_path %></h1>
        <h1><%= link_to "Users", users_path %></h1>
      </ul>
    </div>
    <div class="table-responsive">
      <table class="table table-striped">
        <div class="article-new-wrapper">
          <div class="container">
            <div class="row">
              <div class="col-md-6 col-md-offset-3">
                <h1 class="text-center">NEW ARTICLE</h1>
                <%= form_for @article,:url => {:action => :create} do |f| %>
                  <div class="form-group">
                    <%= f.label :image %>
                    <%= f.file_field :image %>
                  </div>
                  <div class="form-group">
                    <%= f.label :title %>
                    <%= f.text_area :title, class: 'form-control' %>
                  </div>
                  <div class="form-group">
                    <%= f.label :content %>
                    <%= f.text_area :content, class: 'form-control' %>
                  </div>
                  <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </table>
    </div>
</body>

app/views/articles/index.html.erb
<div class="review-index-wrapper">
  <div class="container">
    <% @articles.each do |article| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="review-index-single">
            <h2 class="review-author">
              <%= article.title %>
            </h2>
            <%= image_tag article.image.url %>
            <p class="article-text">
              <%= article.content %>
            </p>
            <p><%= article.master.name %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>