config/routes.rb
Rails.application.routes.draw do
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'sessions/new'
  resources 'users'
  
  namespace :admin do
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :masters, :apps, :articles, :campsites, :gears
  end
  
  resources :reviews, :campsites, :articles, :gears
  
  
  root 'pages#index'
  get 'pages/help'
  
  get  'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites',to: 'favorites#destroy'

  get 'comments/index'
  get 'comments/new' 
  post '/comments', to: "comments#create"
  delete '/comments', to: "comments#destroy"
end

app/models/app.rb
class App < ApplicationRecord
  has_many :masters
  has_many :articles
  has_many :gears
  has_many :campsites
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :master_id, presence: true
  validates :content, presence: true
  validates :image, presence: true
  default_scope -> { order(created_at: :desc) }
  
  mount_uploader :image, ImageUploader
  
  belongs_to :master
  has_many :reviews
end

app/models/campsite.rb
class Campsite < ApplicationRecord
  belongs_to :master
  has_many :reviews
  
  
  validates :master_id, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/gear.rb
class Gear < ApplicationRecord
  validates :master_id, presence: true
  
  belongs_to :master
  has_many :reviews
end

app/models/master.rb
class Master < ApplicationRecord
  validates :name,presence: true, length:{maximum:15}
  validates :login_id,presence: true, length:{maximum:15}
  validates :admin,presence: true
  
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]/
  validates :email,presence: true, format:{with:VALID_EMAIL_REGEX}
  
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])[a-z\d]{8,32}+\z/
  validates :password, presence: true, format:{with:VALID_PASSWORD_REGEX}
  
  has_secure_password
  
  has_many :users
  has_many :articles
  has_many :gears
  has_many :campsites
end

app/models/review.rb
class Review < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true
  default_scope -> { order(created_at: :desc) }
  
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  has_many :comments, dependent: :destroy
  has_many :comment_users, through: :comments, source: 'user'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,presence: true, length:{maximum:15}
  
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]/
  validates :email,presence: true, format:{with:VALID_EMAIL_REGEX}
  
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])[a-z\d]{8,32}+\z/
  validates :password, presence: true, format:{with:VALID_PASSWORD_REGEX}
  
  has_secure_password
  
  has_many :reviews, dependent: :destroy
  has_many :favorites
  has_many :favorite_reviews, through: :favorites, source: 'review'
  has_many :comments
  has_many :comments_reviews, through: :comments, source: 'review'
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @user = User.all
  end
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  def index
    @gears = Gear.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました"
    redirect_to users_url
  end
  
  def show
    @user = current_user.name
    @reviews = Review.where(user_id: current_user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/campsites_helper.rb
module CampsitesHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def create
    master = Master.find_by(email: params[:session][:email])
    if master && master.authenticate(params[:session][:password])
      log_in master
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end
  
  
  private
  def master_params
    params.require(:masters).permit(:login_id, :eamil, :password, :password_confirmation)
  end
  def log_in(master)
    session[:masters] = master.id
  end

  def log_out(master)
    session.delete(:masters)
    @current_master = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<body>
    <h1>管理画面</h1>
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <h1><%= link_to "Article", admin_articles_path %></h1>
        <h1><%= link_to "Gaers", admin_gears_path %></h1>
        <h1><%= link_to "Campsites", admin_campsites_path %></h1>
        <h1><%= link_to "Users", users_path %></h1>
      </ul>
    </div>
    <div class="table-responsive">
      <table class="table table-striped">
        <h1>All User</h1>
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
          </ul>
        </div>
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
              </tr>
            </thead>
            <tbody>
              <% @user.each do |user| %>
                <tr>
                  <td><%= user.name %></td>
                  <td><%= user.email %></td>
                  <td><%= link_to 'Show', user %></td>
                  <td><%= link_to 'Edit', edit_user_path(user) %></td>
                  <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
                </tr>
              <% end %>
            </tbody>
        </div>
      </table>
    </div>
</body>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign in</h1>
          <%= form_for @user do |f| %>
            <div class="form-group">
              <%= f.label :name, class: 'text-white' %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :email, class: 'text-white' %>
              <%= f.text_field :email, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :password, class: 'text-white' %>
              <%= f.password_field :password, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :password_confirmation, class: 'text-white' %>
              <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
            
            <%= f.submit "登録", class: 'btn-block btn-white' %>
          <% end %>
          <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="review-index-wrapper">
  <div class="container">
    <% @reviews.each do |review| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= link_to '新規投稿', new_review_path, class: 'btn btn-primary' %>
          <div class="review-index-single">
            <h2 class="review-author">
              <%= review.user.name %>
            </h2>
            <%= image_tag review.image.url %>
            <% if !review.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(review_id: review.id), method: :post do %>
                <%= image_tag 'icons/heart-black.png', class: 'like-btn' %>
              <% end %>
            <% else %>
              <%= link_to favorites_path(review_id: review.id), method: :delete do %>
                <%= image_tag 'icons/heart-black.png', class: 'unlike-btn' %>
              <% end %>
            <% end %>
            <%= review.favorite_users.count %>
            <%= link_to comments_new_path(review_id: review.id),remote: true do %>
              <%= image_tag 'icons/comment.png', class: 'review-index-icon ' %>
            <% end %>
            <p class="review-text">
              <%= review.description %>
            </p>
            <h4 class="comment-title">投稿コメント</h4>
            
            <div id=<%= "comment_new#{review.id}" %>></div>
            
            <% review.comments.each do |comment| %>
              <p><%= comment.body %></p>
            <% end %>
            <%= link_to '編集', edit_review_path(review), class: 'btn btn-primary' %>
            <%= link_to 'Destroy', review, method: :delete, class: 'btn btn-danger btn-xs' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>